name: gym_lab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
  - family: Jost
    fonts:
      - asset: fonts/Jost-ExtraLight.ttf
        weight: 200
      - asset: fonts/Jost-Light.ttf
        weight: 300
      - asset: fonts/Jost-Regular.ttf
        weight: 400
      - asset: fonts/Jost-Medium.ttf
        weight: 500
      - asset: fonts/Jost-SemiBold.ttf
        weight: 600
      - asset: fonts/Jost-Bold.ttf
        weight: 700
      - asset: fonts/Jost-ExtraBold.ttf
        weight: 800
  

 